version: "3.9"
services:
  roblox_itembuyer:
    image: nottekks/roblox_itembuyer:latest
    container_name: roblox_itembuyer
    restart: unless-stopped
    environment:
      - COOKIE=<YOUR COOKIE HERE>